import {useEffect,useState} from 'react';
import {approveCommand,fetchCommands,requestCommand} from '../api/incidents';
import {COMMAND_LABELS,COMMAND_TYPES,type CommandType,type RecoveryCommand} from '../domain/commands';
const canOperate=(role:string|null)=>['admin','mission_commander','flight_controller'].includes(role??'');
export function RecoveryPanel({incidentId,incidentStatus,role,disabled,onCompleted}:{incidentId:string;incidentStatus:string;role:string|null;disabled:boolean;onCompleted():void}){
  const [items,setItems]=useState<RecoveryCommand[]|null>(null);const [error,setError]=useState('');const [pending,setPending]=useState(false);const [type,setType]=useState<CommandType>('CLOSE_ISOLATION_VALVE');const [thrust,setThrust]=useState(60);
  const load=()=>{const c=new AbortController();setError('');void fetchCommands(incidentId,c.signal).then(value=>{setItems(value);setError('');}).catch(error=>{if(!c.signal.aborted&&!(error instanceof DOMException&&error.name==='AbortError'))setError('Could not load recovery commands.');}).finally(()=>setItems(v=>v??[]));return()=>c.abort();};
  useEffect(load,[incidentId]);
  async function mutate(action:'request'|'approve',command?:RecoveryCommand){if(disabled||pending)return;const c=new AbortController();setPending(true);setError('');try{if(action==='request')await requestCommand(incidentId,type,type==='REDUCE_THRUST'?{thrustPercent:thrust}:{},incidentStatus,c.signal);else if(command)await approveCommand(command.id,command.status,c.signal);const next=await fetchCommands(incidentId,c.signal);setItems(next);onCompleted();}catch{setError('Command action failed. Refresh and verify authorization.');}finally{setPending(false);}}
  return <section className="recovery-panel" aria-label="Recovery commands" aria-busy={pending}><h4>Recovery commands</h4><p className={error?'incident-error':'incident-meta'} role="status">{error||(!items?'Loading recovery commands…':items.length===0?'No recovery commands recorded.':'Human-authorized command history')}</p>
    {canOperate(role)&&<form noValidate className="recovery-form" onSubmit={e=>{e.preventDefault();void mutate('request');}}><label htmlFor="recovery-command">Command</label>{/* Native select: platform popup behavior is accepted. */}<select id="recovery-command" value={type} disabled={disabled||pending} onChange={e=>setType(e.target.value as CommandType)}>{COMMAND_TYPES.map(value=><option key={value} value={value}>{COMMAND_LABELS[value]}</option>)}</select>{type==='REDUCE_THRUST'&&<><label htmlFor="recovery-thrust">Thrust percent</label><input id="recovery-thrust" type="number" min={20} max={90} value={thrust} aria-describedby="recovery-thrust-help" onChange={e=>setThrust(Number(e.target.value))}/><p id="recovery-thrust-help" className="incident-meta">Allowed range: 20–90 percent.</p></>}<button type="submit" disabled={disabled||pending}>Request command</button></form>}
    {items&&items.length>0&&<ul className="recovery-list">{items.map(item=><li key={item.id}><strong>{COMMAND_LABELS[item.commandType]}</strong><p className="incident-meta">{item.riskLevel} · {item.status.replaceAll('_',' ')}</p>{item.riskLevel==='critical'&&item.status==='pending_approval'&&<p>Requires two distinct mission commanders or administrators.</p>}{item.result&&<p>{item.result.message}</p>}{item.status==='pending_approval'&&canOperate(role)&&<button type="button" disabled={disabled||pending||(item.commandType==='RESTART_FLIGHT_COMPUTER'&&!['admin','mission_commander'].includes(role??''))} onClick={()=>void mutate('approve',item)}>Approve command</button>}</li>)}</ul>}
  </section>;
}
