export const COMMAND_TYPES=['CLOSE_ISOLATION_VALVE','REDUCE_THRUST','ENTER_SAFE_MODE','RESTART_FLIGHT_COMPUTER'] as const;
export type CommandType=typeof COMMAND_TYPES[number];
export type CommandStatus='pending_approval'|'approved'|'executing'|'completed'|'failed'|'rejected'|'cancelled'|'expired';
export interface RecoveryCommand{id:string;incidentId:string;spacecraftId:string;commandType:CommandType;parameters:Record<string,unknown>;status:CommandStatus;riskLevel:'medium'|'high'|'critical';requestedBy:string;expiresAt:string;createdAt:string;updatedAt:string;result:{success:boolean;message:string;changedFields:string[]}|null;errorMessage:string|null}
const types=new Set<string>(COMMAND_TYPES);const statuses=new Set(['pending_approval','approved','executing','completed','failed','rejected','cancelled','expired']);
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Malformed command response');return v as Record<string,unknown>};
const text=(v:unknown)=>{if(typeof v!=='string'||!v)throw new Error('Malformed command response');return v};
export function parseCommand(v:unknown):RecoveryCommand{const r=object(v);const type=text(r.commandType);const status=text(r.status);const risk=text(r.riskLevel);if(!types.has(type)||!statuses.has(status)||!['medium','high','critical'].includes(risk))throw new Error('Malformed command response');const result=r.result===null?null:object(r.result);const changedFields=result?.changedFields;if(result&&(typeof result.success!=='boolean'||!Array.isArray(changedFields)))throw new Error('Malformed command response');return{id:text(r.id),incidentId:text(r.incidentId),spacecraftId:text(r.spacecraftId),commandType:type as CommandType,parameters:object(r.parameters),status:status as CommandStatus,riskLevel:risk as RecoveryCommand['riskLevel'],requestedBy:text(r.requestedBy),expiresAt:new Date(text(r.expiresAt)).toISOString(),createdAt:new Date(text(r.createdAt)).toISOString(),updatedAt:new Date(text(r.updatedAt)).toISOString(),result:result?{success:result.success as boolean,message:text(result.message),changedFields:(changedFields as unknown[]).map(text)}:null,errorMessage:r.errorMessage===null?null:text(r.errorMessage)};}
export function parseCommandList(v:unknown){if(!Array.isArray(v)||v.length>50)throw new Error('Malformed command response');return v.map(parseCommand);}
export const COMMAND_LABELS:Record<CommandType,string>={CLOSE_ISOLATION_VALVE:'Close isolation valve',REDUCE_THRUST:'Reduce thrust',ENTER_SAFE_MODE:'Enter safe mode',RESTART_FLIGHT_COMPUTER:'Restart flight computer'};
